

epochs: 100
batch_size: 256


lr: 0.0005
weight_decay: 1e-4

num_workers: 24


emb_size: 256
heads: 8
depth: 4
n_channels: 18
n_fft: 250
hop_length: 125
mask_ratio: 0.75

early_stopping_patience: 10
save_every: 10

dataset_path: "../../Datasets/Bipolar/TUH/Dataset_bipolar_TUH"
log_dir: ./logs/pretrain-new
